const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';

const TAB_BOTTOM_NAVI_SHOW = 'TAB_BOTTOM_NAVI_SHOW';
const TAB_BOTTOM_NAVI_UNSHOW = 'TAB_BOTTOM_NAVI_UNSHOW';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,

    TAB_BOTTOM_NAVI_SHOW,
    TAB_BOTTOM_NAVI_UNSHOW
}