const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';

const TAB_BOTTOM_NAVI_SHOW = 'TAB_BOTTOM_NAVI_SHOW';
const TAB_BOTTOM_NAVI_UNSHOW = 'TAB_BOTTOM_NAVI_UNSHOW';
const TAB_BOTTOM_NAVI_SELECT_CHANGE = 'TAB_BOTTOM_NAVI_SELECT_CHANGE';

const POP_SHOW = 'POP_SHOW';
const POP_UNSHOW = 'POP_UNSHOW';
const POP_STATE_CHANGE = 'POP_STATE_CHANGE';

const GET_USER_INFO = 'GET_USER_INFO';
const SET_INVITE_ME_CODE = 'SET_INVITE_ME_CODE';
const SET_LOGIN_STATE = 'SET_LOGIN_STATE';

const ADD_APP_INFO_URL = 'ADD_APP_INFO_URL';

const READ_AUTO_BUY_TRUE = 'READ_AUTO_BUY_TRUE';
const READ_AUTO_BUY_FALSE = 'READ_AUTO_BUY_FALSE';
const READ_AUTO_BUY_CHANGE = 'READ_AUTO_BUY_CHANGE';

const CLEAR_LOCAL_STORAGE = 'CLEAR_LOCAL_STORAGE';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,

    TAB_BOTTOM_NAVI_SHOW,
    TAB_BOTTOM_NAVI_UNSHOW,
    TAB_BOTTOM_NAVI_SELECT_CHANGE,

    POP_SHOW,
    POP_UNSHOW,
    POP_STATE_CHANGE,

    GET_USER_INFO,
    SET_INVITE_ME_CODE,
    SET_LOGIN_STATE,

    ADD_APP_INFO_URL,

    READ_AUTO_BUY_TRUE,
    READ_AUTO_BUY_FALSE,
    READ_AUTO_BUY_CHANGE,

    CLEAR_LOCAL_STORAGE,
}